// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
//
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
//
// Example 2:
// Input: s = "", t = "y"
// Output: "y"
//
// Constraints:
//
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

import 'testable.dart';

class Solution {
  String findTheDifference(String s, String t) {
    var xor = 0;
    s.codeUnits.forEach((codeUnit) => xor ^= codeUnit);
    t.codeUnits.forEach((codeUnit) => xor ^= codeUnit);

    return String.fromCharCode(xor);
  }
}

class SolutionTest extends Testable<String> with ConsoleTestOutput {
  final String s, t;

  SolutionTest({required this.s, required this.t, required super.result});

  @override
  String computeResult() => Solution().findTheDifference(s, t);
}

void main(List<String> args) {
  [
    SolutionTest(s: "abcd", t: "abcde", result: "e"),
    SolutionTest(s: "", t: "y", result: "y"),
  ].test();
}
